/**
 * SINGLE SOURCE OF TRUTH for every public route on itsjoshmoore.com.
 *
 * Four things are derived from this one table, so they cannot drift apart:
 *
 *   1. client/src/App.tsx        — the wouter <Switch> is generated from it, and the
 *                                  component map is typed by `RoutePath`, so adding a
 *                                  route here without a page (or a page without an
 *                                  entry here) is a TypeScript error.
 *   2. client/src/hooks/useSeo   — `useRouteSeo("/about")` reads title/description
 *                                  from here for client-side navigation.
 *   3. dist/public/<file>        — scripts/prerender-seo.ts writes one real HTML file
 *                                  per route at build time, with this route's title,
 *                                  description, canonical and og tags baked into the
 *                                  source HTML (crawlers and link unfurlers do not run
 *                                  JavaScript, so the useSeo effect never fires for them).
 *   4. dist/public/sitemap.xml   — generated by the same script.
 *
 * Adding a public route = add one entry here + one line in App.tsx's PAGES map.
 * Nothing in vercel.json needs to change: Vercel's `cleanUrls` serves
 * dist/public/about.html at /about straight off the filesystem.
 */

/**
 * Canonical origin. The apex (itsjoshmoore.com) 308-redirects to www at the domain
 * level, so www is the only host that may ever appear in a canonical or og:url.
 */
export const SITE_ORIGIN = "https://www.itsjoshmoore.com";

/** Absolute URL of the shared Open Graph card image. */
export const OG_IMAGE_URL = `${SITE_ORIGIN}/og-image.jpg`;

export interface RouteSeo {
  /** Route path as wouter matches it, and as the canonical URL is built. */
  readonly path: string;
  /** Output file, relative to the build output root (dist/public). */
  readonly file: string;
  /** Full <title> for this route. */
  readonly title: string;
  /** Meta description for this route. */
  readonly description: string;
  /** sitemap.xml <lastmod>. Bump by hand when the page's content actually changes. */
  readonly lastmod: string;
  readonly changefreq: "weekly" | "monthly" | "yearly";
  readonly priority: string;
}

export const SITE_ROUTES = [
  {
    path: "/",
    file: "index.html",
    title: "Josh Moore | Creative Finance Real Estate Investor in Michigan",
    description:
      "Josh Moore uses creative financing to buy single family, multifamily, commercial, RV park and mobile home park deals in Michigan and beyond.",
    lastmod: "2026-08-16",
    changefreq: "weekly",
    priority: "1.0",
  },
  {
    path: "/buy-box",
    file: "buy-box.html",
    title: "Buy Box | What Josh Moore Is Buying",
    description:
      "Investment criteria for single family, commercial multifamily, mobile home park and RV park deals: price caps, unit counts, markets, financing and deal killers.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.9",
  },
  {
    path: "/submit-deal",
    file: "submit-deal.html",
    title: "Submit a Deal | Josh Moore",
    description:
      "Send Josh Moore a property to review. A short guided form covering single family, multifamily, mobile home park and RV park / campground deals.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.9",
  },
  {
    path: "/about",
    file: "about.html",
    title: "About Josh Moore | Creative Real Estate Investor",
    description:
      "Josh Moore's story, core values and areas of expertise: seller financing, subject-to, lease options and wraps across residential and commercial property.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.8",
  },
  {
    path: "/househackingguide",
    file: "househackingguide.html",
    title: "Live In, Rent Smart | Free House Hacking Guide by Josh Moore",
    description:
      "A free beginner's guide to house hacking. Download the PDF or read it online to lower your housing cost, learn the numbers and buy with a plan.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.8",
  },
  {
    path: "/collaborate",
    file: "collaborate.html",
    title: "Collaborate with Josh Moore",
    description:
      "An intake form for bird dogs, wholesalers, private and hard money lenders, capital partners, brokers and other industry partners who want to work together.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/resources",
    file: "resources.html",
    title: "Resources for Real Estate Investors | Josh Moore",
    description:
      "Tools and services Josh Moore recommends: investor-friendly insurance, hard money and construction lending, free West Michigan deal finder training, and AI tools.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.7",
  },
  {
    path: "/contact",
    file: "contact.html",
    title: "Contact Josh Moore | Book a Call",
    description:
      "Schedule a time with Josh Moore to talk through a deal or a partnership, and follow along on Instagram, TikTok, X, Threads and LinkedIn.",
    lastmod: "2026-08-16",
    changefreq: "monthly",
    priority: "0.6",
  },
  {
    path: "/privacy",
    file: "privacy.html",
    title: "Privacy Policy | Josh Moore",
    description:
      "How itsjoshmoore.com collects, uses and shares the information you provide through the deal submission and contact forms.",
    lastmod: "2026-08-16",
    changefreq: "yearly",
    priority: "0.3",
  },
] as const satisfies readonly RouteSeo[];

/** Union of every valid public route path, e.g. "/" | "/about" | ... */
export type RoutePath = (typeof SITE_ROUTES)[number]["path"];

/**
 * Build the canonical URL for a route path.
 * Root keeps its slash ("/"); every other path is emitted without a trailing slash.
 * `trailingSlash: false` in vercel.json makes the server agree: /about/ 308s to /about.
 */
export function canonicalUrl(path: string): string {
  const withSlash = path.startsWith("/") ? path : `/${path}`;
  if (withSlash === "/") return `${SITE_ORIGIN}/`;
  return `${SITE_ORIGIN}${withSlash.replace(/\/+$/, "")}`;
}

/** Look up a route's metadata. Throws on an unknown path rather than silently no-op. */
export function getRoute(path: RoutePath): RouteSeo {
  const route = SITE_ROUTES.find((r) => r.path === path);
  if (!route) {
    throw new Error(
      `[seo-routes] No entry for "${path}". Add it to SITE_ROUTES in shared/seo-routes.ts.`,
    );
  }
  return route;
}
