/**
 * Post-build step: turn the single Vite-built SPA shell into one real HTML file per
 * route, with that route's <title>, description, canonical and og tags baked into the
 * SOURCE HTML — then emit sitemap.xml from the same table.
 *
 * Why this exists
 * ---------------
 * Crawlers' indexing pass and every link unfurler (LinkedIn, Facebook, X, Slack,
 * iMessage) read the raw HTML and never execute JavaScript. Serving one shared
 * index.html for all routes meant every URL advertised the homepage's title,
 * description, canonical and og:url — a self-canonicalisation that tells Google the
 * sub-pages are duplicates of "/", and a share card that shows homepage copy for the
 * lead-magnet page. Runtime `useSeo` cannot fix that; only bytes on the wire can.
 *
 * How it is served
 * ----------------
 * vercel.json sets `cleanUrls: true`, so Vercel serves dist/public/about.html at
 * /about straight off the filesystem — no rewrite list to keep in sync. Unknown
 * paths still miss the filesystem and get a real HTTP 404 with 404.html as the body.
 *
 * Run: `tsx scripts/prerender-seo.ts` (wired into `pnpm build`).
 */
import { readFileSync, writeFileSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  canonicalUrl,
  SITE_ROUTES,
  type RouteSeo,
} from "../shared/seo-routes.ts";

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const outDir = path.join(repoRoot, "dist", "public");
const shellPath = path.join(outDir, "index.html");

/** Escape a value for use inside a double-quoted HTML attribute. */
function attr(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

/** Escape a value for use as HTML text content. */
function text(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
}

/** Escape a value for use inside XML text (sitemap <loc>). */
function xml(value: string): string {
  return text(value).replace(/"/g, "&quot;").replace(/'/g, "&apos;");
}

/**
 * Replace exactly one occurrence of `pattern`. Anything other than exactly one match
 * means client/index.html drifted from what this script expects, which would silently
 * ship wrong canonicals — so fail the build instead.
 */
function replaceOnce(
  html: string,
  pattern: RegExp,
  replacement: string,
  label: string,
  file: string,
): string {
  const matches = html.match(new RegExp(pattern.source, pattern.flags + "g"));
  const count = matches ? matches.length : 0;
  if (count !== 1) {
    throw new Error(
      `[prerender-seo] Expected exactly 1 "${label}" tag in ${file}, found ${count}. ` +
        `Fix the tag in client/index.html or the pattern in scripts/prerender-seo.ts.`,
    );
  }
  return html.replace(pattern, () => replacement);
}

function renderRoute(shell: string, route: RouteSeo): string {
  const url = canonicalUrl(route.path);
  let html = shell;

  html = replaceOnce(
    html,
    /<title>[\s\S]*?<\/title>/,
    `<title>${text(route.title)}</title>`,
    "<title>",
    route.file,
  );
  html = replaceOnce(
    html,
    /<meta name="description" content="[^"]*"\s*\/?>/,
    `<meta name="description" content="${attr(route.description)}" />`,
    "meta description",
    route.file,
  );
  html = replaceOnce(
    html,
    /<link rel="canonical" href="[^"]*"\s*\/?>/,
    `<link rel="canonical" href="${attr(url)}" />`,
    "link canonical",
    route.file,
  );
  html = replaceOnce(
    html,
    /<meta property="og:url" content="[^"]*"\s*\/?>/,
    `<meta property="og:url" content="${attr(url)}" />`,
    "og:url",
    route.file,
  );
  html = replaceOnce(
    html,
    /<meta property="og:title" content="[^"]*"\s*\/?>/,
    `<meta property="og:title" content="${attr(route.title)}" />`,
    "og:title",
    route.file,
  );
  html = replaceOnce(
    html,
    /<meta property="og:description" content="[^"]*"\s*\/?>/,
    `<meta property="og:description" content="${attr(route.description)}" />`,
    "og:description",
    route.file,
  );

  return html;
}

function buildSitemap(): string {
  const entries = SITE_ROUTES.map((route) =>
    [
      "  <url>",
      `    <loc>${xml(canonicalUrl(route.path))}</loc>`,
      `    <lastmod>${route.lastmod}</lastmod>`,
      `    <changefreq>${route.changefreq}</changefreq>`,
      `    <priority>${route.priority}</priority>`,
      "  </url>",
    ].join("\n"),
  ).join("\n");

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<!-- Generated by scripts/prerender-seo.ts from shared/seo-routes.ts. Do not edit by hand. -->',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    entries,
    "</urlset>",
    "",
  ].join("\n");
}

/**
 * Belt-and-braces for the route list.
 *
 * App.tsx generates its <Switch> from SITE_ROUTES and its component map is typed by
 * `RoutePath`, so the normal way of adding a route cannot drift. This catches the
 * abnormal way: someone hand-writing a literal <Route path="/newsletter"> that has no
 * table entry, and therefore no prerendered file — which would work under `vite dev`
 * (it has its own SPA fallback) and hard-404 in production.
 */
function assertNoUntabledRoutes(): void {
  const appPath = path.join(repoRoot, "client", "src", "App.tsx");
  const app = readFileSync(appPath, "utf8");
  const known = new Set<string>([
    ...SITE_ROUTES.map((r) => r.path),
    "/404", // deliberately not in the table: never prerendered, indexed or in the sitemap
  ]);

  const orphans = [...app.matchAll(/<Route[^>]*\spath="([^"]+)"/g)]
    .map((m) => m[1])
    .filter((p) => !known.has(p));

  if (orphans.length > 0) {
    throw new Error(
      `[prerender-seo] client/src/App.tsx declares ${orphans.map((p) => `"${p}"`).join(", ")} ` +
        `with no entry in SITE_ROUTES. Those paths get no prerendered HTML file and would ` +
        `return a hard 404 in production. Add them to shared/seo-routes.ts.`,
    );
  }
}

function main(): void {
  assertNoUntabledRoutes();

  const shell = readFileSync(shellPath, "utf8");

  const root = SITE_ROUTES.find((r) => r.path === "/");
  if (!root || root.file !== "index.html") {
    throw new Error(
      '[prerender-seo] SITE_ROUTES must contain a "/" route whose file is "index.html".',
    );
  }

  const seen = new Set<string>();
  for (const route of SITE_ROUTES) {
    if (seen.has(route.file)) {
      throw new Error(`[prerender-seo] Duplicate output file "${route.file}".`);
    }
    seen.add(route.file);

    const target = path.join(outDir, route.file);
    if (path.relative(outDir, target).startsWith("..")) {
      throw new Error(`[prerender-seo] Refusing to write outside dist/public: ${route.file}`);
    }

    writeFileSync(target, renderRoute(shell, route), "utf8");
    console.log(`[prerender-seo] ${route.path.padEnd(22)} -> dist/public/${route.file}`);
  }

  writeFileSync(path.join(outDir, "sitemap.xml"), buildSitemap(), "utf8");
  console.log(
    `[prerender-seo] sitemap.xml         -> ${SITE_ROUTES.length} URLs`,
  );
}

main();
